extend-exclude = [
  "generated",
]
line-length = 120
preview = true

[analyze]
preview = true

[format]
docstring-code-format = true
preview = true

[lint]
ignore = [
  "any-type",
  "blind-except",
  "complex-structure",
  "missing-copyright-notice",
  "undocumented-public-module",
  "undocumented-public-class",
  "undocumented-public-method",
  "undocumented-public-function",
  "undocumented-public-package",
  "undocumented-magic-method",
  "undocumented-public-nested-class",
  "undocumented-public-init",
  "empty-docstring-section",
  "raw-string-in-exception",
  "f-string-in-exception",
  "boolean-type-hint-positional-argument",
  "boolean-default-value-positional-argument",
  "too-many-public-methods",
  "too-many-return-statements",
  "too-many-branches",
  "too-many-arguments",
  "too-many-locals",
  "too-many-statements",
  "too-many-boolean-expressions",
  "too-many-positional-arguments",
  "unnecessary-assign",
  "explicit-f-string-type-conversion",
  "assert",
  "debugger",
  "typing-only-first-party-import",
  "typing-only-third-party-import",
  "typing-only-standard-library-import",
  "runtime-cast-value",
  "raise-vanilla-args",
  "error-instead-of-exception",
  ####
  "print",
  "datetime-timezone-utc",
  "non-pep695-type-alias",
  "non-pep695-generic-function",
  "magic-value-comparison",
  "too-many-statements-in-try-clause",
  "start-process-with-partial-path",
  "noqa-comments",
  "suspicious-non-cryptographic-random-usage",
  "subprocess-without-shell-equals-true",
  "missing-trailing-comma",
  "unused-method-argument",
  "suspicious-subprocess-import",
]
preview = true
select = ["ALL"]

[lint.flake8-import-conventions.extend-aliases]
"datetime" = "dt"

[lint.flake8-import-conventions.banned-aliases]
"datetime.datetime" = ["dt"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
required-imports = ["from __future__ import annotations"]

[lint.pydocstyle]
convention = "google"
